### ISSUE TITLE
build:scripts randomly failing (OSOE-559)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Orchard-Training-Demo-Module#108]
I've seen [this kind of error](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4078942234/jobs/7029758051) twice during OSOCE CI builds now. Usually, it works, but sometimes we see this:

```
EXEC : error : "build:scripts" exited with 1. [C:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\src\Modules\Lombiq.TrainingDemo\Lombiq.TrainingDemo.csproj]
Error: 1: Command failed: pnpm build [C:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\src\Modules\Lombiq.TrainingDemo\Lombiq.TrainingDemo.csproj]
EXEC : error : "build:scripts" exited with 1. [C:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\src\Modules\Lombiq.TrainingDemo\Lombiq.TrainingDemo.csproj]
EXEC : error : Command failed: pnpm build [C:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\src\Modules\Lombiq.TrainingDemo\Lombiq.TrainingDemo.csproj]
EXEC : error : "build:scripts" exited with 1. [C:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\src\Modules\Lombiq.TrainingDemo\Lombiq.TrainingDemo.csproj]
Error: MSB3073: The command "node scripts/run-pnpm-script "C:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\src\Modules\Lombiq.TrainingDemo" build" exited with code 1. [C:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\src\Modules\Lombiq.TrainingDemo\Lombiq.TrainingDemo.csproj]
```

It seems that the first step would be to increase build output verbosity and wait for it to happen again.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-559)

**Comment by Piedone** [comment]
@0liver is this something that you can look into, please?

**Comment by 0liver** [comment]
I will.

Did the error occur twice in the same project?

**Comment by Piedone** [comment]
Thanks. Yes, I remember it being with Training Demo as well (in OSOCE), but I can't find the build (I've rerun it so can't search for it).

**Comment by Piedone** [comment]
Now this happened differently, seemingly not related to a solution, see [this run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4108084417). We have the binlogs there.

```
[Build and Test - root solution (larger runners) / Build and Test (windows-2022-8core): src/Utilities/Lombiq.NodeJs.Extensions/Lombiq.NodeJs.Extensions/Lombiq.NodeJs.Extensions.targets#L79](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/395/files#annotation_8625591334)
MSB3073: The command "pnpm link C:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\/node_modules/.nx" exited with code 1. [C:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis\Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis.csproj]
```

**Comment by Piedone** [comment]
Now the same [in this run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4186466958/attempts/1).

**Comment by 0liver** [comment]
That last two comment links point to the error that has been fixed by the latest PR: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/408:

![image](https://user-images.githubusercontent.com/164360/224697110-5ba131c2-c3d6-407d-8156-9b760d00473e.png)

But this error is **different** from the one mentioned in the original issue body, which is now being addressed by a new issue: https://github.com/Lombiq/NodeJs-Extensions/issues/39.

**Comment by Piedone** [comment]
Did we see https://github.com/Lombiq/NodeJs-Extensions/issues/39 before this issue has been merged?

So this one should be closed?

**Comment by 0liver** [comment]
https://github.com/Lombiq/NodeJs-Extensions/issues/39 is basically identical with the original issue here.

From the newest comments of yours (Feb 6 and Feb 15) a different error "pushed itself" into the foreground, and the initial error you mentioned in the beginning was henceforth ignored.

It has lately appeared again, though, that's why I've opened the mentioned issue.

I suggest to close this one here, optionally updating the issue description with the error that was ultimately fixed, and address the other error under https://github.com/Lombiq/NodeJs-Extensions/issues/39.
